"""empty message

Revision ID: de8a1ce8a97d
Revises: 
Create Date: 2025-03-26 20:45:04.167006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8a1ce8a97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open_slot', sa.Boolean(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    # ### end Alembic commands ###
